fixed issue-#27
friniaccusonus/LPFplugin pull request #33
Opened 2017-11-01 12:16 UTC by friniaccusonus

2017-11-03 08:59 UTC, kusuri requested changes
Also, I found the following bug

## Steps to reproduce

- load a plugin instance 
- set the filter type menu to  `Custom Filter`
- the automatable parameter is not set to the correct value

2017-11-03 08:59 UTC, kusuri commented on LPFilter/Source/PluginEditor.cpp
> +    filterModeBox.addItemList(StringArray(list, 3), 1);
You could use the `processor.mode->choices` string array

2017-11-03 08:59 UTC, kusuri commented on LPFilter/Source/PluginEditor.cpp
> +        filterModeBox.setSelectedItemIndex(newFilterType);
The notification type should be `dontSendNotification`. Otherwise, this call will trigger the `comboBoxChanged` method.

2017-11-06 11:08 UTC, friniaccusonus commented
# AU issue

There's an issue with the AU format of the plugin, found in Live, Logic and Reaper. 
The  automatable parameter related to the `comboBox` component is not updated properly.

* **Live** : Choosing the third choice in the comboBox doesn't  update the parameter.
* **Logic** : None of the choices in the comboBox updates the parameter.
* **Reaper** : UI is "disabled" when automation is on, so the user can't change the values of the comboBox. Also, during automation the parameter seems to take the values for the first two choices only.

2017-11-06 15:11 UTC, kusuri approved these changes

2017-11-06 15:11 UTC, merged